name: Deploy LMS Engine to Cloud Run

on:
  push:
    branches:
      - staging
  workflow_dispatch:  # Allows manual deployments

jobs:
  versioning:
    runs-on: ubuntu-latest
    outputs:
      new_version: ${{ steps.versioning.outputs.new_version }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Determine Version Bump
        id: versioning
        uses: mathieudutour/github-tag-action@v6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: "v"
          default_bump: "patch"

  build:
    needs: versioning
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Docker Image
        run: |
          docker build -t vicharanashala/calm:${{ needs.versioning.outputs.new_version }} -f prod/lmse.Dockerfile backend/lms_engine/
          docker push vicharanashala/calm:${{ needs.versioning.outputs.new_version }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [staging, production]
    steps:
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy LMS Engine
        run: |
          gcloud run deploy calm-lmse-${{ matrix.environment }} \
            --image=docker.io/vicharanashala/calm:${{ needs.versioning.outputs.new_version }} \
            --region=asia-south2 \
            --project=${{ secrets.GCP_PROJECT_ID }} \
            --set-env-vars=LMSE_DJANGO_ENVIRONMENT=${{ matrix.environment }} \
            --set-env-vars=LMSE_DJANGO_SECRET_KEY=${{ secrets.LMSE_DJANGO_SECRET_KEY }} \
            --set-env-vars=LMSE_DB_HOST=${{ secrets.LMSE_DB_HOST }} \
            --set-env-vars=LMSE_DB_NAME=${{ secrets.LMSE_DB_NAME }} \
            --set-env-vars=LMSE_DB_PASSWORD=${{ secrets.LMSE_DB_PASSWORD }} \
            --set-env-vars=LMSE_DB_PORT=${{ secrets.LMSE_DB_PORT }} \
            --set-env-vars=LMSE_DB_USER=${{ secrets.LMSE_DB_USER }} \
            --set-env-vars=LMSE_ALLOWED_HOSTS=${{ secrets.LMSE_ALLOWED_HOSTS }} \
            --set-env-vars=LMSE_CORS_ALLOWED_ORIGINS=${{ secrets.LMSE_CORS_ALLOWED_ORIGINS }} \
            --set-env-vars=LMSE_SECURE_SSL_REDIRECT=${{ secrets.LMSE_SECURE_SSL_REDIRECT }} \
            --set-env-vars=LMSE_SENTRY_DSN=${{ secrets.LMSE_SENTRY_DSN }} \
            --set-env-vars=LMSE_GCP_BUCKET_NAME=${{ secrets.LMSE_GCP_BUCKET_NAME }} \
            --set-env-vars=LMSE_STATIC_URL=${{ secrets.LMSE_STATIC_URL }} \
            --set-env-vars=LMSE_CSRF_TRUSTED_ORIGINS=${{ secrets.LMSE_CSRF_TRUSTED_ORIGINS }} \
            --set-env-vars=ACTIVITY_ENGINE_URL=${{ secrets.ACTIVITY_ENGINE_URL }} \
            --platform=managed \
            --quiet \
            --no-traffic
          
          gcloud run services update-traffic calm-lmse-${{ matrix.environment }} --to-latest
